name: Build & Deploy to Cloud Run

on:
  push:
    branches:
      - migrate-gcp-heroku

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  REGION: ${{ secrets.REGION }}
  REPO_NAME: ${{github.repository}} # Github Repository
  REPO: ${{ secrets.REPO }} # Artifact Registry Repositiry 

  IMAGE_BASE: ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.REPO }}
  # The COMMIT_TAG (which is the Git commit SHA) provides traceability between your code and deployed images. 
  COMMIT_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    environment: gcp-dev

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List directory contents
        run: |
          pwd
          ls -la

      - name: Authenticate to Google Cloud with WIF
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{secrets.WIF_PROVIDER}}
          service_account: ${{secrets.SERVICE_ACCOUNT}}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
    
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ secrets.ARTIFACT_DOMAIN }}

      # Generate timestamp for image tagging
      - name: Generate timestamp tag
        id: timestamp
        run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
      
      # Delete all existing images
      - name: Delete all existing images
        run: |
          IMAGES=("${{ secrets.IGNITEDAPI }}" "${{ secrets.IGNITEDAPI_WORKERS }}" "${{ secrets.IGNITEDAPI_SCHEDULER }}" "${{ secrets.IGNITED_CHAT_STAGING }}")
          
          for IMAGE in "${IMAGES[@]}"; do
            echo "Deleting all existing images for $IMAGE..."
            
            if gcloud artifacts repositories describe ${{ secrets.REPO }} --location=${{ secrets.REGION }} &>/dev/null; then
              # List all existing digests
              DIGESTS=$(gcloud artifacts docker images list $IMAGE_BASE/$IMAGE --format="value(DIGEST)" 2>/dev/null || echo "")
              
              if [ -n "$DIGESTS" ]; then
                echo "Found existing images for $IMAGE, deleting all of them"
                
                for DIGEST in $DIGESTS; do
                  echo "Deleting image with digest $DIGEST"
                  gcloud artifacts docker images delete $IMAGE_BASE/$IMAGE@$DIGEST --quiet --delete-tags || echo "Failed to delete digest $DIGEST"
                done
              else
                echo "No existing images found for $IMAGE"
              fi
            else
              echo "Repository ${{ secrets.REPO }} doesn't exist yet or is not accessible, skipping cleanup"
            fi
          done
      
      # Build new images with appropriate CMD commands and timestamp tag
      - name: Build new images
        run: |
          TIMESTAMP="${{ steps.timestamp.outputs.TIMESTAMP }}"
          echo "Building images with timestamp tag: $TIMESTAMP"
          
          declare -A IMAGE_CMDS=(
            ["${{ secrets.IGNITEDAPI }}"]='["npm", "start"]'
            ["${{ secrets.IGNITEDAPI_SCHEDULER }}"]='["npm", "workers/scheduled/poc-warning.js"]'
            ["${{ secrets.IGNITEDAPI_WORKERS }}"]='["node", "all-workers.js"]'
            ["${{ secrets.IGNITED_CHAT_STAGING }}"]='["npm", "start"]'
          )

          for IMAGE in "${!IMAGE_CMDS[@]}"; do
            CMD_ARG=${IMAGE_CMDS[$IMAGE]}
            echo "Building $IMAGE with CMD: $CMD_ARG and tag: $TIMESTAMP"
            docker build -t $IMAGE_BASE/$IMAGE:latest -t $IMAGE_BASE/$IMAGE:$TIMESTAMP . \
              --build-arg CMD="$CMD_ARG"
          done

      # Push new images
      - name: Push new images
        run: |
          TIMESTAMP="${{ steps.timestamp.outputs.TIMESTAMP }}"
          for IMAGE in ${{ secrets.IGNITEDAPI }} ${{ secrets.IGNITEDAPI_WORKERS }} ${{ secrets.IGNITEDAPI_SCHEDULER }} ${{ secrets.IGNITED_CHAT_STAGING }}; do
            echo "Pushing $IMAGE:latest and $IMAGE:$TIMESTAMP"
            docker push $IMAGE_BASE/$IMAGE:latest
            docker push $IMAGE_BASE/$IMAGE:$TIMESTAMP
          done