name: Build & Deploy to Cloud Run

# Trigger workflow on any push to the 'migrate-gcp-heroku' branch
on:
  push:
    branches:
      - migrate-gcp-heroku

env:
  # Constructs the base path for container images in Artifact Registry
  IMAGE_BASE: ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.REPO }}
  # Stores the commit SHA for image traceability 
  COMMIT_TAG: ${{ github.sha }}

jobs:
  ######################################################
  # JOB 1: Build the images and deploy them to Artifact Registry repository.
  ######################################################
  build-and-push:
    # if: false 
    runs-on: ubuntu-22.04
    environment: gcp-dev

    # Request necessary permissions for the job
    permissions:
      id-token: write   # Needed for Workload Identity Federation
      contents: read    # Access to the AR repository code

    steps:
      # Step 1: Get the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Debug step to show current directory and files
      - name: List directory contents
        run: |
          pwd
          ls -la
      
      # Step 3: Authenticate to GCP using Workload Identity Federation
      - name: Authenticate to Google Cloud with WIF
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{secrets.WIF_PROVIDER}}
          service_account: ${{secrets.SERVICE_ACCOUNT}}

      # Step 4: Set up the gcloud CLI tools for later GCP operations
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
    
      # Step 5: Configure Docker to use Google Artifact Registry for pushing images
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ secrets.ARTIFACT_DOMAIN }}

      # Step 6: Generate a timestamp for tagging images
      - name: Generate timestamp tag
        id: timestamp
        run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
      
      
      # Step 7: Clean up by deleting all previously existing images in Artifact Registry
      - name: Delete all existing images
        run: |
          IMAGES=("${{ vars.IGNITEDAPI }}" "${{ vars.IGNITEDAPI_WORKERS }}" "${{ vars.IGNITEDAPI_SCHEDULER }}" "${{ vars.IGNITED_CHAT_STAGING }}")
          
          for IMAGE in "${IMAGES[@]}"; do
            echo "Deleting all existing images for $IMAGE..."
            
            # Check if the repository exists before trying to delete images
            if gcloud artifacts repositories describe ${{ secrets.REPO }} --location=${{ secrets.REGION }} &>/dev/null; then

              # Get a list of all image digests to delete
              DIGESTS=$(gcloud artifacts docker images list $IMAGE_BASE/$IMAGE --format="value(DIGEST)" 2>/dev/null || echo "")
              
              if [ -n "$DIGESTS" ]; then
                echo "Found existing images for $IMAGE, deleting all of them"
                
                for DIGEST in $DIGESTS; do
                  echo "Deleting image with digest $DIGEST"
                  gcloud artifacts docker images delete $IMAGE_BASE/$IMAGE@$DIGEST --quiet --delete-tags || echo "Failed to delete digest $DIGEST"
                done
              else
                echo "No existing images found for $IMAGE"
              fi
            else
              echo "Repository ${{ secrets.REPO }} doesn't exist yet or is not accessible, skipping cleanup"
            fi
          done
      
      # Step 8: Build new Docker images with specific commands for each service
      - name: Build new images
        run: |
          TIMESTAMP="${{ steps.timestamp.outputs.TIMESTAMP }}"
          echo "Building images with timestamp tag: $TIMESTAMP"
          
          # Define the CMD instructions for each container using an associative array
          declare -A IMAGE_CMDS=(
            ["${{ vars.IGNITEDAPI }}"]='["npm", "start"]'
            ["${{ vars.IGNITEDAPI_SCHEDULER }}"]='["npm", "workers/scheduled/poc-warning.js"]'
            ["${{ vars.IGNITEDAPI_WORKERS }}"]='["node", "all-workers.js"]'
            ["${{ vars.IGNITED_CHAT_STAGING }}"]='["npm", "start"]'
          )

          # Build each image with its specific CMD and both 'latest' and timestamp tags
          for IMAGE in "${!IMAGE_CMDS[@]}"; do
            CMD_ARG=${IMAGE_CMDS[$IMAGE]}
            echo "Building $IMAGE with CMD: $CMD_ARG and tag: $TIMESTAMP"
            docker build -t $IMAGE_BASE/$IMAGE:latest -t $IMAGE_BASE/$IMAGE:$TIMESTAMP . \
              --build-arg CMD="$CMD_ARG"
          done

      # Step 9: Push all the newly built images to Google Artifact Registry repository
      - name: Push new images
        run: |
          TIMESTAMP="${{ steps.timestamp.outputs.TIMESTAMP }}"
          for IMAGE in ${{ vars.IGNITEDAPI }} ${{ vars.IGNITEDAPI_WORKERS }} ${{ vars.IGNITEDAPI_SCHEDULER }} ${{ vars.IGNITED_CHAT_STAGING }}; do
            echo "Pushing $IMAGE:latest and $IMAGE:$TIMESTAMP"
            docker push $IMAGE_BASE/$IMAGE:latest
            docker push $IMAGE_BASE/$IMAGE:$TIMESTAMP
          done

  ######################################################
  # JOB 2: Second job that depends on the first job completing
  ######################################################
  deploy:
    if: false 
    runs-on: ubuntu-22.04
    needs: build-and-push
    environment: gcp-dev

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud with WIF
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1

      # Deploy each service to Cloud Run
      - name: Deploy to Cloud Run
        continue-on-error: true   # Delete this in the production.
        run: |
          export REGION="${{ secrets.REGION }}"
          export IMAGE_BASE="${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.REPO }}"
          # export TIMESTAMP="${{ steps.timestamp.outputs.TIMESTAMP }}"

          IMAGES=(
            "${{ vars.IGNITEDAPI }}"
            "${{ vars.IGNITEDAPI_WORKERS }}"
            "${{ vars.IGNITEDAPI_SCHEDULER }}"
            "${{ vars.IGNITED_CHAT_STAGING }}"
          )
          
          SERVICES=(
            "${{ vars.IGNITEDAPI_SERVICE }}"
            "${{ vars.IGNITEDAPI_WORKERS_SERVICE }}"
            "${{ vars.IGNITEDAPI_SCHEDULER_SERVICE }}"
            "${{ vars.IGNITED_CHAT_STAGING_SERVICE }}"
          )

          for i in "${!SERVICES[@]}"; do
            SERVICE="${SERVICES[$i]}"
            IMAGE="${IMAGES[$i]}"

            echo "Checking if service $SERVICE exists..."
            if gcloud run services describe "$SERVICE" --region="$REGION" --platform=managed &>/dev/null; then
              echo "Service $SERVICE exists. Deploying image $IMAGE..."
              gcloud run services update "$SERVICE" \
                --image="$IMAGE_BASE/$IMAGE:latest" \
                --region="$REGION" \
                --platform=managed \
                --quiet
            else
              echo "Service $SERVICE does not exist, skipping..."
            fi
          done

  finish:
    if: false 
    name: Finalize Workflow
    runs-on: ubuntu-22.04
    needs: deploy
    steps:
      - name: Workflow Complete
        run: echo "✅ Build and Deploy workflow completed successfully!"
